// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aktahq/proto/config/v1/config.proto

package configv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Logger_Level int32

const (
	Logger_INFO  Logger_Level = 0
	Logger_WARN  Logger_Level = 1
	Logger_ERROR Logger_Level = 2
	Logger_DEBUG Logger_Level = 3
	Logger_TRACE Logger_Level = 4
)

// Enum value maps for Logger_Level.
var (
	Logger_Level_name = map[int32]string{
		0: "INFO",
		1: "WARN",
		2: "ERROR",
		3: "DEBUG",
		4: "TRACE",
	}
	Logger_Level_value = map[string]int32{
		"INFO":  0,
		"WARN":  1,
		"ERROR": 2,
		"DEBUG": 3,
		"TRACE": 4,
	}
)

func (x Logger_Level) Enum() *Logger_Level {
	p := new(Logger_Level)
	*p = x
	return p
}

func (x Logger_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Logger_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_aktahq_proto_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (Logger_Level) Type() protoreflect.EnumType {
	return &file_aktahq_proto_config_v1_config_proto_enumTypes[0]
}

func (x Logger_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Logger_Level.Descriptor instead.
func (Logger_Level) EnumDescriptor() ([]byte, []int) {
	return file_aktahq_proto_config_v1_config_proto_rawDescGZIP(), []int{1, 0}
}

type Logger_Format int32

const (
	Logger_TEXT Logger_Format = 0
	Logger_JSON Logger_Format = 1
)

// Enum value maps for Logger_Format.
var (
	Logger_Format_name = map[int32]string{
		0: "TEXT",
		1: "JSON",
	}
	Logger_Format_value = map[string]int32{
		"TEXT": 0,
		"JSON": 1,
	}
)

func (x Logger_Format) Enum() *Logger_Format {
	p := new(Logger_Format)
	*p = x
	return p
}

func (x Logger_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Logger_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_aktahq_proto_config_v1_config_proto_enumTypes[1].Descriptor()
}

func (Logger_Format) Type() protoreflect.EnumType {
	return &file_aktahq_proto_config_v1_config_proto_enumTypes[1]
}

func (x Logger_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Logger_Format.Descriptor instead.
func (Logger_Format) EnumDescriptor() ([]byte, []int) {
	return file_aktahq_proto_config_v1_config_proto_rawDescGZIP(), []int{1, 1}
}

// App describes the application build config.
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BuildTime     *string                `protobuf:"bytes,2,opt,name=build_time,json=buildTime" json:"build_time,omitempty"`
	BuildRevision *string                `protobuf:"bytes,3,opt,name=build_revision,json=buildRevision" json:"build_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_aktahq_proto_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_aktahq_proto_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_aktahq_proto_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *App) GetBuildTime() string {
	if x != nil && x.BuildTime != nil {
		return *x.BuildTime
	}
	return ""
}

func (x *App) GetBuildRevision() string {
	if x != nil && x.BuildRevision != nil {
		return *x.BuildRevision
	}
	return ""
}

type Logger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *Logger_Level          `protobuf:"varint,1,opt,name=level,enum=aktahq.proto.config.v1.Logger_Level" json:"level,omitempty"`
	Format        *Logger_Format         `protobuf:"varint,2,opt,name=format,enum=aktahq.proto.config.v1.Logger_Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger) Reset() {
	*x = Logger{}
	mi := &file_aktahq_proto_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger) ProtoMessage() {}

func (x *Logger) ProtoReflect() protoreflect.Message {
	mi := &file_aktahq_proto_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger.ProtoReflect.Descriptor instead.
func (*Logger) Descriptor() ([]byte, []int) {
	return file_aktahq_proto_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Logger) GetLevel() Logger_Level {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return Logger_INFO
}

func (x *Logger) GetFormat() Logger_Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return Logger_TEXT
}

var File_aktahq_proto_config_v1_config_proto protoreflect.FileDescriptor

const file_aktahq_proto_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"#aktahq/proto/config/v1/config.proto\x12\x16aktahq.proto.config.v1\"_\n" +
	"\x03App\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"build_time\x18\x02 \x01(\tR\tbuildTime\x12%\n" +
	"\x0ebuild_revision\x18\x03 \x01(\tR\rbuildRevision\"\xdf\x01\n" +
	"\x06Logger\x12:\n" +
	"\x05level\x18\x01 \x01(\x0e2$.aktahq.proto.config.v1.Logger.LevelR\x05level\x12=\n" +
	"\x06format\x18\x02 \x01(\x0e2%.aktahq.proto.config.v1.Logger.FormatR\x06format\"<\n" +
	"\x05Level\x12\b\n" +
	"\x04INFO\x10\x00\x12\b\n" +
	"\x04WARN\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\t\n" +
	"\x05DEBUG\x10\x03\x12\t\n" +
	"\x05TRACE\x10\x04\"\x1c\n" +
	"\x06Format\x12\b\n" +
	"\x04TEXT\x10\x00\x12\b\n" +
	"\x04JSON\x10\x01B,Z*github.com/aktahq-labs/proto-go/configv1pbb\beditionsp\xe8\a"

var (
	file_aktahq_proto_config_v1_config_proto_rawDescOnce sync.Once
	file_aktahq_proto_config_v1_config_proto_rawDescData []byte
)

func file_aktahq_proto_config_v1_config_proto_rawDescGZIP() []byte {
	file_aktahq_proto_config_v1_config_proto_rawDescOnce.Do(func() {
		file_aktahq_proto_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aktahq_proto_config_v1_config_proto_rawDesc), len(file_aktahq_proto_config_v1_config_proto_rawDesc)))
	})
	return file_aktahq_proto_config_v1_config_proto_rawDescData
}

var file_aktahq_proto_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aktahq_proto_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aktahq_proto_config_v1_config_proto_goTypes = []any{
	(Logger_Level)(0),  // 0: aktahq.proto.config.v1.Logger.Level
	(Logger_Format)(0), // 1: aktahq.proto.config.v1.Logger.Format
	(*App)(nil),        // 2: aktahq.proto.config.v1.App
	(*Logger)(nil),     // 3: aktahq.proto.config.v1.Logger
}
var file_aktahq_proto_config_v1_config_proto_depIdxs = []int32{
	0, // 0: aktahq.proto.config.v1.Logger.level:type_name -> aktahq.proto.config.v1.Logger.Level
	1, // 1: aktahq.proto.config.v1.Logger.format:type_name -> aktahq.proto.config.v1.Logger.Format
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aktahq_proto_config_v1_config_proto_init() }
func file_aktahq_proto_config_v1_config_proto_init() {
	if File_aktahq_proto_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aktahq_proto_config_v1_config_proto_rawDesc), len(file_aktahq_proto_config_v1_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aktahq_proto_config_v1_config_proto_goTypes,
		DependencyIndexes: file_aktahq_proto_config_v1_config_proto_depIdxs,
		EnumInfos:         file_aktahq_proto_config_v1_config_proto_enumTypes,
		MessageInfos:      file_aktahq_proto_config_v1_config_proto_msgTypes,
	}.Build()
	File_aktahq_proto_config_v1_config_proto = out.File
	file_aktahq_proto_config_v1_config_proto_goTypes = nil
	file_aktahq_proto_config_v1_config_proto_depIdxs = nil
}
